apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: rest-jwt-app
          image: omka2061/fastapi-rest-jwt-app
          command: ["/bin/sh"]
          args: ["-c", "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"]
          env:
            - name: DB_USER
              value: "root"
            - name: DB_PASS
              value: "omka2061"
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "db"
            - name: SECRET_AUTH
              value: "SECRET"
          ports:
            - containerPort: 8000
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: app
  ports:
  - name: app-port
    port: 8000
    targetPort: 8000
    nodePort: 31000