apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
spec:
  selector:
    matchLabels:
      app: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: rest-jwt-pgadmin
        image: dpage/pgadmin4
        imagePullPolicy: Always
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "mcscare12@gmail.com"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "omka2061"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  type: NodePort
  selector:
    app: pgadmin
  ports:
  - name: pgadmin-port
    port: 80
    targetPort: 80
    nodePort: 30080