name: Build and Deploy

on:
  push:
    branches:
      - master
      - develop

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Create env file'
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env &&
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env &&
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env &&
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env &&
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env &&
          echo "PGADMIN_EMAIL=${{ secrets.PGADMIN_EMAIL }}" >> .env &&
          echo "PGADMIN_PASSWORD=${{ secrets.PGADMIN_PASSWORD }}" >> .env &&
          echo "SECRET_AUTH=${{ secrets.SECRET_AUTH }}" >> .env
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build the stack
        run: docker compose up -d
