name: Build and Deploy

on:
  push:
    branches:
      - master
      - develop

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Create env file'
        run: |
          echo "${{ secrets.DB_HOST }}" >> .env &&
          echo "${{ secrets.DB_NAME }}" >> .env &&
          echo "${{ secrets.DB_PASS }}" >> .env &&
          echo "${{ secrets.DB_PORT }}" >> .env &&
          echo "${{ secrets.DB_USER }}" >> .env &&
          echo "${{ secrets.PGADMIN_EMAIL }}" >> .env &&
          echo "${{ secrets.PGADMIN_PASSWORD }}" >> .env &&
          echo "${{ secrets.SECRET_AUTH }}" >> .env
          
      - name: Build the stack
        run: docker compose up -d
