name: Build and Deploy

on:
  push:
    branches:
      - master
      - develop

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:     
      - uses: jtalk/k8s-deploy@v2
        with:
          manifests: |
              kubernetes/
          kubectl-version: 'latest'
